### ISSUE TITLE
Write Introduction contents for Admin Guide

### ISSUE THREAD

**Issue by r0ckarong** [SUSE/doc-caasp#306]
- [x] [Admin Guide Purpose and explanations](https://github.com/SUSE/doc-caasp/issues/307)
- [x] [Target Audience / Required Knowledge / Skills](https://github.com/SUSE/doc-caasp/issues/305)
- [x] [Workstation description / requirements](https://github.com/SUSE/doc-caasp/issues/308)
~~[Architecture Blueprints](https://github.com/SUSE/doc-caasp/issues/309)~~
