### ISSUE TITLE
Write Security Chapter for Admin Guide

### ISSUE THREAD

**Issue by r0ckarong** [SUSE/doc-caasp#310]
- [x] [Security concepts](https://github.com/SUSE/doc-caasp/issues/311)
- [x] [Managing Users and Groups](https://github.com/SUSE/doc-caasp/issues/312)
- [x] [Role Management (RBAC)](https://github.com/SUSE/doc-caasp/issues/313)
- [x] [LDAP configuration and usage](https://github.com/SUSE/doc-caasp/issues/314)
- [x] [Certificates](https://github.com/SUSE/doc-caasp/issues/315)
- [x] [Pod Security Policies](https://github.com/SUSE/doc-caasp/issues/316)
- [x] [Networking Policies (Cilium)](https://github.com/SUSE/doc-caasp/issues/317)
- [ ] [Security Audit Log](https://github.com/SUSE/doc-caasp/issues/318)
