### ISSUE TITLE
Describe Software Management

### ISSUE THREAD

**Issue by r0ckarong** [SUSE/doc-caasp#319]
- [ ] [Installing software](https://github.com/SUSE/doc-caasp/issues/320)
- [ ] [Updating Cluster nodes](https://github.com/SUSE/doc-caasp/issues/321)
- [ ] [Upgrading CaaSP](https://github.com/SUSE/doc-caasp/issues/322)
- [ ] [Migration](https://github.com/SUSE/doc-caasp/issues/323)

**Comment by r0ckarong** [comment]
Migration not needed. Rest is already described.

**Comment by r0ckarong** [comment]
Relates to #323
