### ISSUE TITLE
Describe Cluster Management

### ISSUE THREAD

**Issue by r0ckarong** [SUSE/doc-caasp#324]
- [x] [Interacting with the cluster](https://github.com/SUSE/doc-caasp/issues/325)
~~[Reserving Compute Resources](https://github.com/SUSE/doc-caasp/issues/326)~~
- [x] [Cluster scaling](https://github.com/SUSE/doc-caasp/issues/327)
- [x] [Node Management](https://github.com/SUSE/doc-caasp/issues/328) (partially covered by #247)
- [X] [Graceful Shutdown and Startup](https://github.com/SUSE/doc-caasp/issues/329)
