### ISSUE TITLE
Describe Disaster Recovery

### ISSUE THREAD

**Issue by r0ckarong** [SUSE/doc-caasp#330]
- [ ] [Backup](https://github.com/SUSE/doc-caasp/issues/331)
- [ ] [Restore](https://github.com/SUSE/doc-caasp/issues/332)
- [ ] [Workload shifting](https://github.com/SUSE/doc-caasp/issues/333)
- [ ] [Data Retention policies](https://github.com/SUSE/doc-caasp/issues/334)
- [ ] [Best Practices](https://github.com/SUSE/doc-caasp/issues/335)

**Comment by r0ckarong** [comment]
March 2020
