### ISSUE TITLE
Describe integration with other SUSE products

### ISSUE THREAD

**Issue by r0ckarong** [SUSE/doc-caasp#339]
- [x] CAP
- [ ] SUSE Manager
- [ ] SUSE Enterprise Storage
- [x] SES as Storage backend (StorageClass with rbd...)
- [x] CPI with SUSE OpenStack Cloud

PM/PO needs to specify which other products we integrate with

**Comment by r0ckarong** [comment]
@kkaempf @qnetter @NunoFilipeSantos Could you please define which products we want/need to describe integrations for and to what detail level.

**Comment by kkaempf** [comment]
[Testing CAP](https://github.com/SUSE/avant-garde/issues/397) is a QA requirement. So we should be able to document this.

SUSE Manager is currently being [experimented with](https://github.com/SUSE/avant-garde/issues/536) and might have an outcome by GA.

I'm not aware of any other requirements.

**Comment by pgonin** [comment]
There is testing with SES as Storage backend (StorageClass with rbd...)
There is also CPI with SUSE OpenStack Cloud

**Comment by qnetter** [comment]
That's the correct list. SUSE Manager for container scanning and (if work is completed in time) deployment or at least init/bootstrap. SES as persistent storage. SOC CPI integration. CAP integration is really part of the CAP docs, but I will check what back-reference they want,

**Comment by jordimassaguerpla** [comment]
CPI: https://susedoc.github.io/doc-caasp/beta/caasp-deployment/single-html/#_enabling_cloud_provider_integration

SES: https://github.com/SUSE/doc-caasp/pull/400

CAP is being handled here: https://github.com/SUSE/doc-caasp/issues/264 and https://github.com/SUSE/doc-caasp/pull/397

@qnetter Do the above look like what you were expecting/would accept for 4.0? Otherwise, can you provide us with some content for the writer team to review?

I don't know about SUSE Manager

**Comment by nkoranova** [comment]
SUSE Manager has an Issue open here: https://github.com/SUSE/spacewalk/issues/8307

**Comment by r0ckarong** [comment]
From our side good for now.
